services:
  credit_application_service_db:
    image: postgres:16.3-alpine
    container_name: credit_application_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: credit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5451:5432"
    volumes:
      - "credit_application_service_db:/var/lib/postgresql/data"
    networks:
      - finteh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d card -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  credit_application_service_db:
    name: credit_application_service_db
